### ISSUE TITLE
pdftoipe fail to compile with poppler 22.12

### ISSUE THREAD

**Issue by us91** [otfried/ipe-tools#57]
It seems that the API for poppler has changed. The change causes pdftoipe to not compile, with the following message:

```
xmloutputdev.cpp:156:21: error: no matching function for call to ‘GfxState::getLineDash(double**, int*, double*)’
  156 |   state->getLineDash(&dash, &length, &start);
      |   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/poppler/Gfx.h:40,
                 from xmloutputdev.cpp:13:
/usr/include/poppler/GfxState.h:1506:32: note: candidate: ‘const std::vector<double>& GfxState::getLineDash(double*)’
 1506 |     const std::vector<double> &getLineDash(double *start)
      |                                ^~~~~~~~~~~
/usr/include/poppler/GfxState.h:1506:32: note:   candidate expects 1 argument, 3 provided
```

**Comment by otfried** [comment]
Have you looked at #55?

**Comment by us91** [comment]
I tried the [https://github.com/otfried/ipe-tools/pull/55](url). But the same problem still persists. It seems the new error I listed above is a new issue because it points to a different function `GfxState::getLineDash`.

**Comment by otfried** [comment]
If you apply the patch in the pull request, then the line 156 shown in your error message no longer exists, so your error must have been produce from the sources without that patch?

**Comment by us91** [comment]
You are right! I cloned the code from #55, but used the `master` branch, instead of the correct `fix-poppler-22.09` branch. After applying both #48 and #55, The problem is fully solved.  Thanks a lot. And I will close the issue.
