### ISSUE TITLE
Failure to compile with poppler 0.69.0

### ISSUE THREAD

**Issue by fxcoudert** [otfried/ipe-tools#29]
The error is:

```
09:45:41 clang++ -Wno-write-strings -I/usr/local/Cellar/poppler/0.69.0/include/poppler  -c -o pdftoipe.o pdftoipe.cpp
09:45:41 pdftoipe.cpp:160:11: error: no type named 'memCheck' in 'Object'
09:45:41   Object::memCheck(stderr);
```

since `Object::memCheck` was removed in https://cgit.freedesktop.org/poppler/poppler/commit/poppler/Object.h?h=poppler-0.69.0&id=c362ab1b97f20c5b73b3bad8d52015f679178748
