### ISSUE TITLE
Problem compiling against poppler 0.82.0

### ISSUE THREAD

**Issue by mrzv** [otfried/ipe-tools#43]
I'm trying to build this on ArchLinux, which currently has poppler 0.82.0, and I'm getting the following errors:
```
g++ -Wno-write-strings -std=c++14 -I/usr/include/poppler   -c -o xmloutputdev.o xmloutputdev.cpp
xmloutputdev.cpp: In member function ‘void XmlOutputDev::doPath(GfxState*)’:
xmloutputdev.cpp:209:33: error: passing ‘const GfxPath’ as ‘this’ argument discards qualifiers [-fpermissive]
  209 |     subpath = path->getSubpath(i);
      |                                 ^
In file included from /usr/include/poppler/Gfx.h:39,
                 from xmloutputdev.cpp:13:
/usr/include/poppler/GfxState.h:1329:15: note:   in call to ‘GfxSubpath* GfxPath::getSubpath(int)’
 1329 |   GfxSubpath *getSubpath(int i) { return subpaths[i]; }
      |               ^~~~~~~~~~
make: *** [<builtin>: xmloutputdev.o] Error 1
```
and
```
g++ -Wno-write-strings -std=c++14 -I/usr/include/poppler   -c -o pdftoipe.o pdftoipe.cpp
pdftoipe.cpp: In function ‘int main(int, char**)’:
pdftoipe.cpp:83:48: error: cannot convert ‘std::_MakeUniq<GlobalParams>::__single_object’ {aka ‘std::unique_ptr<GlobalParams, std::default_delete<GlobalParams> >’} to ‘GlobalParams*’ in assignment
   83 |   globalParams = std::make_unique<GlobalParams>();
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                |
      |                                                std::_MakeUniq<GlobalParams>::__single_object {aka std::unique_ptr<GlobalParams, std::default_delete<GlobalParams> >}
make: *** [<builtin>: pdftoipe.o] Error 1
```

**Comment by otfried** [comment]
As the `readme.txt` says:

```
If there are compilation errors, you most likely have a different
poppler version.  Poppler has changed dramatically during the last
releases, as the developers are updating the code to use modern C++.

If your poppler version is <= v0.68, then you can check out branch
"old-poppler" from the "ipe-tools" repository.  If you have a version
between v0.69 and v0.82 and cannot upgrade poppler easily, you need to
look in the release history below and checkout the right release of
the "ipe-tools" repository. 
```

To compile with poppler 0.82, checking out commit 1bc9c5288ebf9220f696d651fb3cebcb6e355f45 should work.

**Comment by mrzv** [comment]
Got it. Thanks.
