### PR TITLE
pdftoipe: Build with C++20

### PR DESCRIPTION
**Pull request by jbicha**
to fix build with poppler >= 24.04

https://gitlab.freedesktop.org/poppler/poppler/-/commit/d8ae3ba

### CODE REVIEW

**Comment by otfried** [comment]
I don't understand - why does the fact that poppler is now compiled with c++20 require that pdftoipe is compiled with c++20?  Do the poppler header files now use C++20 features?

**Comment by jbicha** [comment]
Sorry for not providing more context. This is the build failure when ipe-tools is built with poppler 24.06.

````
In file included from pdftoipe.cpp:12:
/usr/include/poppler/goo/GooString.h:241:24: error: ‘starts_with’ has not been declared in ‘std::string’
  241 |     using std::string::starts_with;
      |                        ^~~~~~~~~~~
/usr/include/poppler/goo/GooString.h:244:24: error: ‘ends_with’ has not been declared in ‘std::string’
  244 |     using std::string::ends_with;
      |                        ^~~~~~~~~
```

That matches with the poppler commit message where the poppler developer "wsant to use `std::string::starts_with`"

I believe something similar happened years ago which is why pdftoipe specifically required c++17 unlike the rest of this project.

Full log
-----------
https://launchpad.net/ubuntu/+source/ipe-tools/1:7.2.24.1-3.1build4
